server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /api/user/${segment}

        - id: library-service
          uri: http://${LIBRARY_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/library/**
          filters:
            - RewritePath=/library/(?<segment>.*), /api/library/${segment}

        - id: playlist-service
          uri: http://${PLAYLIST_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/playlist/**
          filters:
            - RewritePath=/playlist/(?<segment>.*), /api/playlist/${segment}

#        - id: user-service
#          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
#          predicates:
#            - Path=/users
##            - Method=GET # let through all traffic
#          filters:
#            - SetPath=/api/user
#        - id: library-service
#          uri: http://${LIBRARY_SERVICE_BASEURL:localhost:8082}
#          predicates:
#            - Path=/library
##            - Method=GET # let through all traffic
#          filters:
#            - SetPath=/api/library
#        - id: playlist-service
#          uri: http://${PLAYLIST_SERVICE_BASEURL:localhost:8082}
#          predicates:
#            - Path=/playlist
##            - Method=GET # let through all traffic
#          filters:
#            - SetPath=/api/playlist





#        - id: product-service
#          uri: http://${PRODUCT_SERVICE_BASEURL:localhost:8080}
#          predicates:
#            - Path=/products
#            - Method=POST
#          filters:
#            - SetPath=/api/product
#        - id: product-service-all
#          uri: http://${PRODUCT_SERVICE_BASEURL:localhost:8080}
#          predicates:
#            - Path=/products
#            - Method=GET
#          filters:
#            - SetPath=/api/product/all
#        - id: order-service
#          uri: http://${ORDER_SERVICE_BASEURL:localhost:8081}
#          predicates:
#            - Path=/orders
#          filters:
#            - SetPath=/api/order