apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-user
spec:
  selector:
    matchLabels:
      app: mongo-user
  template:
    metadata:
      labels:
        app: mongo-user
    spec:
      containers:
        - name: mongo-user
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-user-data
              mountPath: /data/db
      volumes:
        - name: mongo-user-data
          persistentVolumeClaim:
            claimName: mongo-user-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-user-pv # The name of this persistent volume
spec:
  capacity: # The storage capacity of this volume
    storage: 1Gi 
  accessModes: # Whether a single node or many nodes can access this volume in read/write or read-only mode.
    - ReadWriteOnce
  hostPath: # location of the data
    path: /data/mongodb 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-user-pvc # The name of this claim. 
spec:
  resources:
    requests: # The storage capacity of this volume
      storage: 1Gi
  accessModes: # Whether a single node or many nodes can access this volume in read/write or read-only mode.
  - ReadWriteOnce
  storageClassName: "" # Must be empty to disable dynamic provisioning.
