apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-library
spec:
  selector:
    matchLabels:
      app: mongo-library
  template:
    metadata:
      labels:
        app: mongo-library
    spec:
      containers:
        - name: mongo-library
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-library-data
              mountPath: /data/db
      volumes:
        - name: mongo-library-data
          persistentVolumeClaim:
            claimName: mongo-library-pvc
