apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-deployment
spec:
  selector:
    matchLabels:
      app: library-deployment
  template:
    metadata:
      labels:
        app: library-deployment
    spec:
      containers:
      - name: library-deployment
        image: tibbovl/library-service:latest
        ports:
        - containerPort: 8082
        env:
          - name: MONGODB_PORT
            value: "27018"
          - name: MONGODB_HOST
            value: mongo-library
          - name: PLAYLIST_SERVICE_BASEURL
            value: playlist-service:8083
          - name: RATING_SERVICE_BASEURL
            value: rating-service:8084

---
apiVersion: v1
kind: Service
metadata:
  name: library-service
spec:
  selector:
    app: library-deployment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
