apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  selector:
    matchLabels:
      app: user-deployment
  template:
    metadata:
      labels:
        app: user-deployment
    spec:
      containers:
      - name: user-deployment
        image: tibbovl/user-servicev3:latest
        ports:
        - containerPort: 8081
        env:
          - name: MONGODB_PORT
            value: "27017"
          - name: MONGODB_HOST
            value: mongo-user-service
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-deployment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
