apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-deployment
spec:
  selector:
    matchLabels:
      app: rating-deployment
  template:
    metadata:
      labels:
        app: rating-deployment
    spec:
      containers:
      - name: rating-deployment
        image: tibbovl/rating-service:latest
        ports:
        - containerPort: 8084
        env:
          - name: MYSQL_DB_USERNAME
            value: "root"
          - name: MYSQL_DB_PASSWORD
            value: "abc123"
          - name: MYSQL_DB_HOST
            value: mysql-rating-service
          - name: MYSQL_DB_PORT
            value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: rating-service
spec:
  selector:
    app: rating-deployment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP
