apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-rating
spec:
  selector:
    matchLabels:
      app: mysql-rating
  template:
    metadata:
      labels:
        app: mysql-rating
    spec:
      containers:
        - name: mysql-rating
          image: mysql:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-rating-data
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "abc123"
      volumes:
        - name: mysql-rating-data
          persistentVolumeClaim:
            claimName: mysql-rating-pvc
